---
- name: Install WordPress, MariaDB, Nginx, and PHP-FPM
  hosts: wordpress-server
#  remote_user: ec2-user
#  become: yes
#  become_method: sudo

  roles:
    - common
    - mariadb
    - nginx
    - php-fpm
    - wordpress
